dataset:
  name: "MNIST"
  data_dir: "./data/mnist"
  download: False
  # initial_transform_script: "./transforms/initial_transforms.py"
  # runtime_transform_script: "./transforms/runtime_transforms.py"

dataloader:
  train:
    num_workers: 0
    batch_size: 64
    drop_last: True
    persistent_workers: False
    shuffle: True
    pin_memory: True

  test:
    num_workers: 0
    batch_size: 64
    drop_last: False
    persistent_workers: False
    shuffle: False
    pin_memory: False

training:
  model_file: "./models/mlp.py"
  model_class: "MLP"
  learning_rate: 0.001

output:
  # Placeholder for output properties
  save_dir: "./output"
