dataset:
  name: "MNIST"
  data_dir: "./data/mnist"
  download: False
  initial_transform_script: "./transforms/initial_transforms.py" # Path to user-defined initial transforms
  runtime_transform_script: "./transforms/runtime_transforms.py" # Path to user-defined runtime transforms

training:
  # Placeholder for training properties
  learning_rate: 0.001

output:
  # Placeholder for output properties
  save_dir: "./output"
