dataset:
  name: "CIFAR10"
  data_dir: "./data/cifar10"
  download: True
  # initial_transform_script: "./transforms/initial_transforms.py"
  # runtime_transform_script: "./transforms/runtime_transforms.py"

dataloader:
  train:
    num_workers: 0
    batch_size: 100
    drop_last: True
    persistent_workers: False
    shuffle: True
    pin_memory: True

  test:
    num_workers: 0
    batch_size: 500
    drop_last: False
    persistent_workers: False
    shuffle: False
    pin_memory: False

training:
  # model_file: "./models/mlp.py"
  # model_class: "MLP"
  model: "resnet18_cifar10"
  epochs: 100
  loss: "CrossEntropyLoss"
  device: "cuda"
  optimizer:
    name: "SGD" # or "Adam", "AdamW", "RMSprop"
    params:
      lr: 0.005
      momentum: 0.9
      weight_decay: 0.005
      nesterov: True
  scheduler:
    name: "ReduceLROnPlateau"
    mode: "min"
    factor: 0.1
    patience: 5

  early_stop: # Optional early stopping parameters
    patience: 5
    delta: 0.01
    monitor_metric: "best_test_accuracy"

logging:
  tensorboard: true

output:
  save_dir: "./output/cifar10"
