wandb_version: 1

learning_rate:
  value: 0.001
model:
  value: PreActResNet18
momentum:
  value: 0.9
optimizer:
  value: Adam
runtime_transform_script:
  value: transforms/runtime_transform_basic.py
weight_decay:
  value: 0.0001
